# Generated by Django 4.0.5 on 2022-06-08 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_comment_name_alter_comment_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='type',
            field=models.CharField(default='general', max_length=100),
        ),
    ]
