# Generated by Django 4.0.5 on 2022-08-12 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_articles_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='link',
            field=models.URLField(blank=True, default='#', max_length=500),
        ),
    ]
